name: run tests and create vimdocs

on:
  push:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest
    name: install neovim and run tests
    steps:
      - uses: actions/checkout@v3
      - name: Get Date
        id: get-date
        run: |
          echo "date=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_OUTPUT
        shell: bash
      - uses: actions/cache@v3
        with:
          path: _neovim
          key: neovim-${{ runner.os }}-x64-${{ steps.get-date.outputs.date }}
      - name: Install neovim.
        run: |
          test -d _neovim || {
            mkdir -p _neovim
            curl -sL "https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz" | tar xzf - --strip-components=1 -C "${PWD}/_neovim"
          }
      - name: Install test dependencies.
        run: |
          git clone https://github.com/nvim-lua/plenary.nvim
      - name: Run tests.
        run: |
          export PATH="${PWD}/_neovim/bin:${PATH}"
          export VIM="${PWD}/_neovim/share/nvim/runtime"
          nvim --version
          make test
  generate_vimdoc:
    runs-on: ubuntu-latest
    name: markdown and lua emmydoc to vimdoc
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Get Date
        id: get-date
        run: |
          echo "date=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_OUTPUT
        shell: bash
      - uses: actions/cache@v3
        with:
          path: _neovim
          key: neovim-${{ runner.os }}-x64-${{ steps.get-date.outputs.date }}
      - name: Install neovim.
        run: |
          test -d _neovim || {
            mkdir -p _neovim
            curl -sL "https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz" | tar xzf - --strip-components=1 -C "${PWD}/_neovim"
          }
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: teaman
          pandoc: doc/teaman.md
          treesitter: true
      - uses: actions/cache@v3
        with:
          path: ./lemmy-help
          key: lemmy-help-${{ runner.os }}-x64-${{ steps.get-date.outputs.date }}
      - name: install lemmy-help
        run: |
          test -x ./lemmy-help || {
            curl -Lq https://github.com/numToStr/lemmy-help/releases/latest/download/lemmy-help-x86_64-unknown-linux-gnu.tar.gz | tar xz
          }
      - name: insert api docs
        run: |
          (
            head -n -3 ./doc/teaman.txt
            ./lemmy-help --no-modeline ./lua/teaman/*.lua
            echo 'Generated by lemmy-help <https://github.com/numToStr/lemmy-help> and panvimdoc <https://github.com/kdheepak/panvimdoc>'
            echo ''
            tail -n 1 ./doc/teaman.txt
          ) > ./doc/teaman.txt
      - name: generate-helptags
        run: |
          export PATH="${PWD}/_neovim/bin:${PATH}"
          export VIM="${PWD}/_neovim/share/nvim/runtime"
          nvim "+helptags ./doc | q"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto generate vimdocs"
          branch: ${{ github.head_ref }}
          file_pattern: doc/teaman.txt doc/tags
