name: panvimdoc

on:
  push:
    branches:
      - main

jobs:
  vimdocgen:
    runs-on: ubuntu-latest
    name: pandoc to vimdoc
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: lemmy-help
        run: |
          curl -Lq https://github.com/numToStr/lemmy-help/releases/latest/download/lemmy-help-x86_64-unknown-linux-gnu.tar.gz | tar xz
          ./lemmy-help ./lua/teaman/*.lua > ./doc/teaman_api.txt
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: teaman
          pandoc: doc/teaman.md
          treesitter: true
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto generate vimdocs"
          branch: ${{ github.head_ref }}
          file_pattern: doc/*.txt
